### ISSUE TITLE
Send Batch example does not work

### ISSUE THREAD

**Issue by bryanklewis** [Azure/azure-event-hubs-go#127] opened 2019-08-07 20:54 UTC
### Expected Behavior
From the [README.md](https://github.com/Azure/azure-event-hubs-go#sending-batches-of-events) the following example is provided:
```
batch := &EventBatch{
            Events: []*eventhub.Event { 
                eventhub.NewEventFromString("one"),
                eventhub.NewEventFromString("two"),
            },
        }
err := client.SendBatch(ctx, batch)
```
### Actual Behavior
The example provided on the README.md for using SendBatch does not actually work. It looks like SendBatch was changed with this commit:
https://github.com/Azure/azure-event-hubs-go/commit/e7ca69248db0ae51aa6c8ca86ed9fd1c60b1a21f

It is not clear how to use the new version of SendBatch().

### Environment
- OS: Windows 10
- Go version: 1.12.7
- Version of Library: v2.0.0

**Comment by gavinfish** [comment] 2019-08-08 01:32
@bryanklewis you could try something like this:
```go
	events := make([]*eventhub.Event, batchSize)
	for i := 0; i < batchSize; i++ {
		// init events
	}
        err = hub.SendBatch(ctx, eventhub.NewEventBatchIterator(events...))
```

**Comment by bryanklewis** [comment] 2019-08-08 03:12
@gavinfish that does not seem to work either. I got a panic.

Code:
```golang
package main

import (
	"context"
	"fmt"
	eventhub "github.com/Azure/azure-event-hubs-go/v2"
	"time"
)

func main() {
	connString := "{your_connection_string_here}"
	batchSize := 3

	hub, _ := eventhub.NewHubFromConnectionString(connString)

	events := make([]*eventhub.Event, batchSize)
	for i := 0; i < batchSize; i++ {
		events = append(events, eventhub.NewEventFromString("one"))
		events = append(events, eventhub.NewEventFromString("two"))
		events = append(events, eventhub.NewEventFromString("three"))
	}

	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	err := hub.SendBatch(ctx, eventhub.NewEventBatchIterator(events...))
	if err != nil {
		fmt.Println(err)
	}
}
```

Results:
```dos
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x8e9693]

goroutine 1 [running]:
github.com/Azure/azure-event-hubs-go/v2.(*EventBatch).Add(0xc0002920f0, 0x0, 0x24, 0xc, 0x6635623700000010)
        C:/Users/myuser/go/pkg/mod/github.com/!azure/azure-event-hubs-go/v2@v2.0.0/batch.go:115 +0x33
github.com/Azure/azure-event-hubs-go/v2.(*EventBatchIterator).Next(0xc000004fe0, 0xc0002a6300, 0x24, 0xc000298180, 0x0, 0x0, 0xf524b0)
        C:/Users/myuser/go/pkg/mod/github.com/!azure/azure-event-hubs-go/v2@v2.0.0/batch.go:82 +0xfb
github.com/Azure/azure-event-hubs-go/v2.(*Hub).SendBatch(0xc00004c720, 0xb11560, 0xc00004c7e0, 0xb08160, 0xc000004fe0, 0x0, 0x0, 0x0, 0x0, 0x0)
        C:/Users/myuser/go/pkg/mod/github.com/!azure/azure-event-hubs-go/v2@v2.0.0/hub.go:668 +0x2b0
main.main()
        C:/Users/myuser/Desktop/event-adapter/main.go:26 +0x5a1
```

**Comment by gavinfish** [comment] 2019-08-08 03:24
I think this is caused by the missing `eventID` for each event, but the error message here is unclear.

**Comment by bryanklewis** [comment] 2019-08-08 03:29
Thats seems to be the right track, in my application, the actual line the panic referred to was [here](https://github.com/Azure/azure-event-hubs-go/blob/38494a72e59457e16aa0645b9534e83bc3130cfa/batch.go#L115). Is that a bug in the library or do i need an eventID waiting for each event added? Since it gets over-written by e.PartitionKey = eb.PartitionKey, seems like the library should account for no ID field.

**Comment by gavinfish** [comment] 2019-08-08 03:50
Setting `eventID` when constructing events should mitigate the issue. But you are right, I think we should  consider no ID field situation. If the `eventID` is necessary when creating an event, I prefer to treat it as a constructor parameter, otherwise users probably will miss it. 

What do you think? @devigned

**Comment by bryanklewis** [comment] 2019-08-08 04:27
@gavinfish constructing the slice with this line:
```golang
events := make([]*eventhub.Event, batchSize)
```
 for example with batchSize 3 to the make() statement causes the constructed object to be filled with 3 nil Events. Its those nil events that are then causing the error when passed to func (eb *EventBatch) Add(e *Event) (bool, error).

**Comment by gavinfish** [comment] 2019-08-08 04:48
@bryanklewis you are right. The error is not related with the eventID stuff. I have just double checked your sample code. The init code should be some like this if you want to use `append`:

```
package main

import (
	"context"
	"fmt"
	eventhub "github.com/Azure/azure-event-hubs-go/v2"
	"time"
)

func main() {
	connString := "{your_connection_string_here}"

	hub, _ := eventhub.NewHubFromConnectionString(connString)

	var events []*eventhub.Event

	events = append(events, eventhub.NewEventFromString("one"))
	events = append(events, eventhub.NewEventFromString("two"))
	events = append(events, eventhub.NewEventFromString("three"))


	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	err := hub.SendBatch(ctx, eventhub.NewEventBatchIterator(events...))
	if err != nil {
		fmt.Println(err)
	}
}
```

otherwise you can use make like this:

```
package main

import (
	"context"
	"fmt"
	"time"

	"github.com/Azure/azure-event-hubs-go/v2"
)

func main() {
	connString:= ""

	batchSize := 3

	hub, _ := eventhub.NewHubFromConnectionString(connString)

	events := make([]*eventhub.Event, batchSize)
	for i := 0; i < batchSize; i++ {
		events[i] = eventhub.NewEventFromString(string(i))
	}

	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	err := hub.SendBatch(ctx, eventhub.NewEventBatchIterator(events...))
	if err != nil {
		fmt.Println(err)
	}
}
```

**Comment by bryanklewis** [comment] 2019-08-08 05:01
Thanks @gavinfish, that helps. Either way, need some better examples of batch send in the docs :-)

**Comment by MartinKosicky** [comment] 2019-08-08 11:49
The iterator does not work, (partition key is missing in the batch event). Batch ends up in random partition even when you specify PartitionKey for each event.

**Comment by devigned** [comment] 2019-08-08 11:56
A batch can only be committed to a single partition. If more than one event in a batch has a different partition, the batch will fail. 

The batch iterator may send events to a different partition on each iteration, but for each iteration all the events in that iteration must be committed to the same partition (per the Event Hubs service).

**Closed** 2019-09-02 08:39 UTC
