### ISSUE TITLE
Event hubs stop receiving data

### ISSUE THREAD

**Issue by connor4312** [Azure/azure-event-hubs-go#122] opened 2019-07-31 17:43 UTC
### Expected Behavior

We can read from an event hub partition and continue receiving data forever, or until an error is returned.

### Actual Behavior

We stop receiving data after some time. This happens particularly frequently under high RPS. Here's the code we have. We've used a timer and a reset in order to kill and then retry receiving data if we don't get events for a given amount of time. Here's a simplified version of the code we're using:

```go
const readerIdleReset = time.Second * 30

func (e *EventHubReader) readFrom(partition string) (listener *eventhub.ListenerHandle, err error) {
	resetTimer := time.NewTimer(readerIdleReset)

	receive := func(_ context.Context, event *eventhub.Event) error {
		message := &rpc.QueueEvent{}
		if err := message.Unmarshal(event.Data); err != nil {
			// error handling
		}

		resetTimer.Reset(readerIdleReset)

		e.data <- message
    
		return nil
	}

	listener, err = e.hub.Receive(context.Background(), partition, receive,
		eventhub.ReceiveWithLatestOffset())
	if err != nil {
		return nil, err
	}

	go func() {
		select {
		case <-resetTimer.C:
			ctx, cancel := context.WithTimeout(context.Background(), e.timeout)
			_ = listener.Close()
			cancel()
		case <-listener.Done():
		}
	}()

	return listener, err
}
```

We detect timeouts by receiving from `listener.Done()` and seeing if the resulting error was `context.Canceled`

One suspicious we had was `e.data <- message` taking a long time, but we added telemetry here that logged any sends which took more than a second, and they were never tripped.

### Environment
- OS: Linux/CentOS
- Go version: 1.12
- Version of Library: v2.0.0

go.sum:

```
github.com/Azure/azure-amqp-common-go/v2 v2.0.0 h1:98xtMbghfioKloSBZgkIwH/SINcDYtxXBbUZoqCePiI=
github.com/Azure/azure-amqp-common-go/v2 v2.0.0/go.mod h1:YDoDY50iQ2OabOP0WUQoNR7vpDjRlB13vIZVrvUoJLo=
github.com/Azure/azure-event-hubs-go/v2 v2.0.0 h1:ZzYGZOBxlB5Y2ZL0aGypSOYHTAWd3hKoWlLZH0CLuIY=
github.com/Azure/azure-event-hubs-go/v2 v2.0.0/go.mod h1:HqOqkORXit1YOUS7CWSVkS+r+2l6yG85YPbOs+01rYU=
github.com/Azure/azure-pipeline-go v0.1.8/go.mod h1:XA1kFWRVhSK+KNFiOhfv83Fv8L9achrP7OxIzeTn1Yg=
github.com/Azure/azure-pipeline-go v0.1.9/go.mod h1:XA1kFWRVhSK+KNFiOhfv83Fv8L9achrP7OxIzeTn1Yg=
github.com/Azure/azure-sdk-for-go v29.0.0+incompatible/go.mod h1:9XXNKU+eRnpl9moKnB4QOLf1HestfXbmab5FXxiDBjc=
github.com/Azure/azure-sdk-for-go v30.0.0+incompatible h1:6o1Yzl7wTBYg+xw0pY4qnalaPmEQolubEEdepo1/kmI=
github.com/Azure/azure-sdk-for-go v30.0.0+incompatible/go.mod h1:9XXNKU+eRnpl9moKnB4QOLf1HestfXbmab5FXxiDBjc=
github.com/Azure/azure-storage-blob-go v0.6.0/go.mod h1:oGfmITT1V6x//CswqY2gtAHND+xIP64/qL7a5QJix0Y=
```

**Comment by devigned** [comment] 2019-07-31 22:44
Can you build your code with `-tags debug` and execute the process with `DEBUG_LEVEL=3`. This should output protocol debugging info to stdout. From that, we should be able to diagnose what is going on.

@gavinfish we should probably review the logs together to help diagnose the issue.

**Comment by connor4312** [comment] 2019-07-31 23:06
Dropped a build on a box with those settings. I'll send logs to you via email once we hit a timeout. Thanks!

**Comment by connor4312** [comment] 2019-08-01 00:33
Sent. Interestingly, amqp logs that it still gets data even up to the point where we timeout (meaning, the function hasn't been called for 30 seconds).

```
00:04:14.868640 RX(Session): Transfer{Handle: 0, DeliveryID: <nil>, DeliveryTag: "<nil>", MessageFormat: <nil>, Settled: false, More: false, ReceiverSettleMode: <nil>, State: <nil>, Resume: false, Aborted: false, Batchable: false, Payload [size]: 368}
00:04:14.868647 RX: Transfer{Handle: 0, DeliveryID: <nil>, DeliveryTag: "<nil>", MessageFormat: <nil>, Settled: false, More: false, ReceiverSettleMode: <nil>, State: <nil>, Resume: false, Aborted: false, Batchable: false, Payload [size]: 368}
00:04:14.868664 RX(Session): Transfer{Handle: 0, DeliveryID: 55955, DeliveryTag: "", MessageFormat: 0, Settled: true, More: true, ReceiverSettleMode: <nil>, State: <nil>, Resume: false, Aborted: false, Batchable: true, Payload [size]: 450}
00:04:14.868671 RX: Transfer{Handle: 0, DeliveryID: 55955, DeliveryTag: "", MessageFormat: 0, Settled: true, More: true, ReceiverSettleMode: <nil>, State: <nil>, Resume: false, Aborted: false, Batchable: true, Payload [size]: 450}
00:04:14.868691 RX(Session): Transfer{Handle: 0, DeliveryID: <nil>, DeliveryTag: "<nil>", MessageFormat: <nil>, Settled: false, More: false, ReceiverSettleMode: <nil>, State: <nil>, Resume: false, Aborted: false, Batchable: false, Payload [size]: 363}
00:04:14.868698 RX: Transfer{Handle: 0, DeliveryID: <nil>, DeliveryTag: "<nil>", MessageFormat: <nil>, Settled: false, More: false, ReceiverSettleMode: <nil>, State: <nil>, Resume: false, Aborted: false, Batchable: false, Payload [size]: 363}
Aug 01 00:04:15 constellation-pulsar1.dal09.mixer.com pulsar[21332]: 00:04:15.151254 TX(Session): Detach{Handle: 0, Closed: true, Error: *Error(nil)}
Aug 01 00:04:15 constellation-pulsar1.dal09.mixer.com pulsar[21332]: time="2019-08-01T00:04:15Z" level=warning msg="event hub read timed out" error="event hub read timed out" partition=4
```

So this seems like it might be something internal to the client or our usage of it. Trying to wrap everything inside the `receive()` function into a spawned goroutine, and then immediately returning nil, didn't seem to do much, so I don't think it's that method backing up.

**Comment by gavinfish** [comment] 2019-08-01 09:02
1. I think there is no need to introduce `timer.Reset()` to make the diagnosis more complex. It should be a potential temporary solution to mitigate your situation but won't be much help for the debug.
2. Is it possible to provide clean code to be able to reproduce the error stably? 

@devigned  any more information could we get from the amqp log?

**Comment by LukaszBrygala** [comment] 2019-09-06 18:08
It looks like I also observed similar issue. After couple of hours of consuming messages from 32 partitions (~ 104 messages / second on each partition) my consumer stopped receiving messages one one of them. Actually, it didn't stop completely, it was still receiving something like 0.5 message / minute. That situation last for around 25 minutes after which consumer suddenly started to consume messages from lagging partition and was able to catch up other partitions.

Situation like this happens for me about 2 times per 24 hours.

I'm running my consumer as single Go application consuming all 32 partitions on Intel(R) Xeon(R) Platinum 8168 CPU @ 2.70GHz (8 cores machine). I'm still using version 1.3.1 of package, I'm planning to upgrade soon.

**Comment by PeterUherek** [comment] 2020-03-10 12:43
We have the same problem. Is there any news or progress in this bug?

**Comment by philpearl** [comment] 2021-09-22 13:44
I think I'm seeing the same problem. We have a hub with 2 partitions and about 1 day's backlog of data. I have a small test program that's trying to read out the entire backlog from the beginning. It reads a portion of the backlog data quite quickly, then slows to a crawl. I've never seen it read all the data

At the beginning the app reports the partitions as follows
```
partition 0
seq 704004 -> 756295
last enqueued offset 210459036960 at 2021-09-22 13:14:20.561 +0000 UTC

partition 1
seq 703687 -> 756296
last enqueued offset 210458954384 at 2021-09-22 13:14:20.544 +0000 UTC
```
I wait until the app stops using any significant CPU, then stop it. It reports the latest sequence number it has seen on each partition as follows.

```
PID 0 last sequence 721902 - offset 197600997384 at 2021-09-22 02:25:55.689 +0000 UTC
PID 1 last sequence 739886 - offset 206162259808 at 2021-09-22 07:16:20.531 +0000 UTC
```

If I wait much much longer (hours) then the received sequence numbers do appear to go up, but very slowly and I've not waited long enough to see them reach the initial reported last enqueued sequence numbers.

The code I'm using to read from the hub is here: https://gist.github.com/philpearl/62cb8a514f82787df65e2fb14c2c2a9e. I can't share the EventHub I'm reading from, but let me know if that would be useful and I may be able to arrange something.

**Comment by philpearl** [comment] 2021-09-22 14:05
If I update the program to use a file persister and restart the program once it has slowed to a crawl, then it reads quickly from the saved position when it restarts. Eventually it grinds to a halt again until I restart it.

**Comment by philpearl** [comment] 2021-09-27 12:53
My problem seems to be that I accidentally used an old version of the event hubs library - you really need to make sure you use the v3 version (at least), not the v1 version that's the default. Make sure you use `github.com/Azure/azure-event-hubs-go/v3` (or check if there's a later version)

**Comment by richardpark-msft** [comment] 2021-12-02 21:20
Closing this issue in favor of #240.

**Closed by richardpark-msft** 2021-12-02 21:20 UTC
