### ISSUE TITLE
not enough arguments in call to client.ListByNamespace

### ISSUE THREAD

**Issue by exztinct01** [Azure/azure-event-hubs-go#46] opened 2018-07-06 15:26 UTC
### Expected Behavior
I expect the go get to finish successfully

### Actual Behavior
C:\Users\Musterion>go get -u github.com/Azure/azure-event-hubs-go/...
# github.com/Azure/azure-event-hubs-go/internal/test
Development\go\src\github.com\Azure\azure-event-hubs-go\internal\test\suite.go:177:34: not enough arguments in call to client.ListByNamespace
        have (context.Context, string, string)
        want (context.Context, string, string, *int32, *int32)

### Environment
- OS: Windows 10
- Go version: go1.10.2 windows/amd64
- Version of Library: latest

**Comment by devigned** [comment] 2018-07-06 15:42
This is a duplicate of #44.

I've reference a branch in #44 which has this change included. I'll merge those changes by end of day.

If you'd like to resolve this problem prior to that, you can use `dep` to ensure you have the correct dependency versions, or you could check out the `timeout` branch.

**Closed by devigned** 2018-07-06 15:42 UTC
