### ISSUE TITLE
Event hubs eventually stop writing

### ISSUE THREAD

**Issue by connor4312** [Azure/azure-event-hubs-go#80] opened 2018-12-06 23:06 UTC
### Expected Behavior

We can write using a single event hub instance forever happily.

### Actual Behavior

After some time, the client begins erroring. It goes along for a while, a week this time, and then starts experiencing failures.

![](https://memes.peet.io/img/18-12-3fmvtqgf3e0obdwz6kiikcocecexme.png)

Once a failure happens on an instance of a service, all requests fail until that service is restarted, with the following error returned from `hub.Send`:

```
Dec 06 21:45:52 interactive5.dal09.mixer.com tetrisd2[4539]: time="2018-12-06T21:45:52Z" level=warning msg="<reacted error>: read tcp <internal ip>:33282->104.208.144.8:5671: read: connection reset by peer"
Dec 06 21:46:37 interactive5.dal09.mixer.com tetrisd2[4539]: time="2018-12-06T21:46:37Z" level=warning msg="<reacted error>: read tcp <internal ip>:33282->104.208.144.8:5671: read: connection reset by peer"
Dec 06 21:46:42 interactive5.dal09.mixer.com tetrisd2[4539]: time="2018-12-06T21:46:42Z" level=warning msg="<reacted error>: read tcp <internal ip>:33282->104.208.144.8:5671: read: connection reset by peer"
```

This tends to happen on one server at a time, and often (but not always) start on the other servers. In this case, within two hours of the first server dropping, four other servers also started experiencing the issue. We see this happening on two different services, on different hardware writing to different event hubs.

In both services the event hub is instantiated with:

```go
tokenProvider, err := sas.NewTokenProvider(tokenProviderFromConnectionString(config.EventHub.ConnectionString))
if err != nil {
    panic(errors.Wrap(err, "app/services: could not create Event Hub token provider"))
}
hub, err := eventhub.NewHub(config.EventHub.Namespace, config.EventHub.Name, tokenProvider)
if err != nil {
    panic(errors.Wrap(err, "app/services: could not create Event Hub instance"))
}

// tokenProviderFromConnectionString creates a TokenProviderOption with the
// given event hub connection string.
func tokenProviderFromConnectionString(connectionString string) sas.TokenProviderOption {
	return func(provider *sas.TokenProvider) error {
		parsed, err := conn.ParsedConnectionFromStr(connectionString)
		if err != nil {
			return err
		}
		return sas.TokenProviderWithKey(parsed.KeyName, parsed.Key)(provider)
	}
}
```

After which we simply use the `hub.Send` method with an unspecified partition.

### Environment
- OS: Linux CentOS
- Go version: 1.10
- Version of Library: ae13e763e548768631bfd505943f8c8d614af76f  with Azure/azure-amqp-common-go@1f0fa230acfce331c18a804d061260622dcd0906

**Comment by devigned** [comment] 2018-12-11 23:35
That's code you shouldn't have to write 😊. I'm working on the fix now. 

Glad to hear the stop gap working!

**Comment by connor4312** [comment] 2018-12-14 16:41
I see there was a PR merged for the issue--thanks! This issue takes a while to come up and we're going into the holidays with limited availability and deployment freezes, so we'll probably wait until January to try rolling back our stopgap and giving that a spin 🙂

**Comment by devigned** [comment] 2018-12-14 16:51
My pleasure!

Totally understand about holiday stability. I'll leave this issue open. Let me know how things go after the holiday.

Cheers!

**Comment by devigned** [comment] 2019-04-18 18:33
Closing due to age. Please reopen if the issue is not fixed.

**Closed by devigned** 2019-04-18 18:33 UTC
Labels: bug

**Comment by connor4312** [comment] 2019-07-31 17:26
Hey, sorry for the lack of followup here. We've updated to the latest version of this library this morning and are still seeing timeouts happening every few minutes. We recover with the retry code posted above, but under high rps timeouts seem more frequent, which is a concern for us. Here's the version snippet from our go.sum

```
github.com/Azure/azure-amqp-common-go/v2 v2.0.0 h1:98xtMbghfioKloSBZgkIwH/SINcDYtxXBbUZoqCePiI=
github.com/Azure/azure-amqp-common-go/v2 v2.0.0/go.mod h1:YDoDY50iQ2OabOP0WUQoNR7vpDjRlB13vIZVrvUoJLo=
github.com/Azure/azure-event-hubs-go/v2 v2.0.0 h1:ZzYGZOBxlB5Y2ZL0aGypSOYHTAWd3hKoWlLZH0CLuIY=
github.com/Azure/azure-event-hubs-go/v2 v2.0.0/go.mod h1:HqOqkORXit1YOUS7CWSVkS+r+2l6yG85YPbOs+01rYU=
github.com/Azure/azure-pipeline-go v0.1.8/go.mod h1:XA1kFWRVhSK+KNFiOhfv83Fv8L9achrP7OxIzeTn1Yg=
github.com/Azure/azure-pipeline-go v0.1.9/go.mod h1:XA1kFWRVhSK+KNFiOhfv83Fv8L9achrP7OxIzeTn1Yg=
github.com/Azure/azure-sdk-for-go v29.0.0+incompatible/go.mod h1:9XXNKU+eRnpl9moKnB4QOLf1HestfXbmab5FXxiDBjc=
github.com/Azure/azure-sdk-for-go v30.0.0+incompatible h1:6o1Yzl7wTBYg+xw0pY4qnalaPmEQolubEEdepo1/kmI=
github.com/Azure/azure-sdk-for-go v30.0.0+incompatible/go.mod h1:9XXNKU+eRnpl9moKnB4QOLf1HestfXbmab5FXxiDBjc=
github.com/Azure/azure-storage-blob-go v0.6.0/go.mod h1:oGfmITT1V6x//CswqY2gtAHND+xIP64/qL7a5QJix0Y=
```

**Comment by rwngallego** [comment] 2021-01-19 16:26
@devigned We have experienced something like this while using `v3.3.0` in a production environment. Basically, after a transient network issue, the connection turned into a bad and unrecoverable state, and we had to restart the whole system in order to recover it. Somehow it impacted the two nodes we have. After looking into the code:

```go
...
	case *amqp.Error, *amqp.DetachError, net.Error:
		if netErr, ok := err.(net.Error); ok {
			if !netErr.Temporary(){
				return netErr
			}
		}
...
```

We have seen that `netErr.Temporary()` is not 100% accurate to identify something that you could consider as "not transient". In our case, we don't know exactly the underlying network issue (we just saw `read tcp IP_HERE:33282->104.208.144.8:5671: read: connection reset by peer`) However, while looking at the Go http library, there could be cases where a `SyscallError (read tcp)` could be misleading in defining a temporary error. Take into consideration [this example](https://github.com/golang/go/commit/7f6105f138b3836e9ad85b8da26d44c742bf217b), one could also consider `UnknownNetworkError` which is also considered as not temporary.

That being said, we gain more reliability using the backoff mechanism than failing promptly. (Actually, what is the gain by failing promptly?) We suggest to remove that temporary conditional and rely on the already present backoff strategy instead:

```go
switch err.(type) {
	case *amqp.Error, *amqp.DetachError, net.Error:
		recvr(err)
	default:
```

Of course, we could implement a recovery logic in our side on top of this library but that would be almost the same approach taken by @connor4312, and a hacky way to solve it: cast the `net.Error` error  returned by `Send()`, implement almost the same backoff mechanism you have here, discard the hub instance and retry.

**Comment by kwontae** [comment] 2021-11-04 21:20
@rwngallego @devigned  We are also witnessing these errors. 
`read tcp <internal ip>:34428-><eventhub ip>:5671: read: connection reset by peer,`

We are using
github.com/Azure/azure-amqp-common-go/v3 v3.0.0
github.com/Azure/azure-event-hubs-go/v3 v3.3.0
github.com/Azure/go-amqp v0.12.8 // indirect

This is the code we have that sends a batch of events to eventhub that we are testing and seeing this error

```
//Send is a function send payload to an event hub
func (eha *HubAgent) Send(ep EventPreparer, jobIDOpt ...string) error {
	jobID := ""
	if len(jobIDOpt) > 0 {
		jobID = jobIDOpt[0]
	}
	errChan := make(chan error, 1)
	threadChan := make(chan int, eha.threadPoolSize)
	//close channels before exiting
	defer close(errChan)
	defer close(threadChan)

	//populate thread channel
	for i := 1; i <= eha.threadPoolSize; i++ {
		threadChan <- i
	}
	g, _ := errgroup.WithContext(context.Background())
	countInBatch := 0
	//listen for an avaialble thread spawn a goroutine per batch
	for threadID := range threadChan {
		if ep.BatchIndex < 0 {
			break
		}
		batch := ep.GetBatch()
		countInBatch += len(batch)
		g.Go(func() error {
			//grab a batch
			//move pointer to next batch
			eha.logger.InfoTrace(fmt.Sprintf("job id: %s is being sent", jobID), eha.region)
			eha.sendBatch(threadID, jobID, batch, errChan, threadChan)
			eha.logger.InfoTrace(fmt.Sprintf("job id: %s Sent %v devices in batch to collector", jobID, len(batch)))
			select {
			case err := <-errChan:
				return err
			default:
				return nil
			}
		})
	}
	//wait for all batches to be sent
	if err := g.Wait(); err != nil {
		return err
	}
	eha.logger.InfoTrace(fmt.Sprintf("job id: %s Processed and sent %v devices in total", jobID, countInBatch))
	return nil
}

func (eha *HubAgent) sendBatch(threadID int, jobID string, batch []*eventhub.Event, errChan chan error, threadChan chan int) {
	retryCount := 1
	ctx, cancel := context.WithTimeout(context.Background(), 60*time.Second)
	defer cancel()
	err := eha.hub.SendBatch(ctx, eventhub.NewEventBatchIterator(batch...))
	for retryCount < 4 && err != nil {
		//retry after retryCount * retryCount seconds
		time.Sleep(time.Duration(retryCount*retryCount) * time.Second)
		err = eha.hub.SendBatch(ctx, eventhub.NewEventBatchIterator(batch...))
		retryCount++
	}
	if err != nil {
		errChan <- fmt.Errorf("thread %d: error sending batchID %s of events to the event hub: %v, discarded %v devices in batch",
			threadID, jobID, err, len(batch))
	}
	eha.logger.InfoTrace(fmt.Sprintf("thread %d: executed after %d retries", threadID, retryCount), eha.region)
	threadChan <- threadID
}
```
